import React, { forwardRef } from 'react';
import { Bar } from 'react-chartjs-2';

const DashboardPrint = forwardRef(({ data, createChartData }, ref) => (
    <div ref={ref} className="printable-content">
        <header className="print-header">
            <h1 className="text-3xl font-bold mb-4">Election Results</h1>
        </header>
        <main>
            {data.elections.map(election => (
                <div key={election.id} className="mb-8">
                    <h2 className="text-2xl font-semibold mb-6">{election.name}</h2>
                    <table className="min-w-full mb-4 border-collapse border border-gray-200">
                        <thead>
                            <tr>
                                <th className="px-4 py-2 border">Position</th>
                                <th className="px-4 py-2 border">Candidate</th>
                                <th className="px-4 py-2 border">Votes</th>
                            </tr>
                        </thead>
                        <tbody>
                            {election.positions.map(position => (
                                position.candidates.map((candidate, index) => (
                                    <tr key={candidate.id}>
                                        {index === 0 && (
                                            <td className="px-4 py-2 border" rowSpan={position.candidates.length}>
                                                {position.name}
                                            </td>
                                        )}
                                        <td className="px-4 py-2 border">{candidate.name}</td>
                                        <td className="px-4 py-2 border">{candidate.votes_count}</td>
                                    </tr>
                                ))
                            ))}
                        </tbody>
                    </table>
                    <div className='grid md:grid-cols-2 grid-cols-1 gap-8'>
                        {election.positions.map(position => (
                            <div key={position.id} className="mb-8">
                                <h3 className="text-lg font-semibold mb-4">{position.name}</h3>
                                <Bar data={createChartData(position)} className='border p-1' />
                            </div>
                        ))}
                    </div>
                </div>
            ))}
        </main>
        <footer className="print-footer">
            <p className="text-center text-sm text-gray-500">Generated by Election System</p>
        </footer>
    </div>
));

export default DashboardPrint;
